using DocumentFormat.OpenXml.Drawing.Charts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Threading.Tasks;

namespace Digimon1
{
    public class Enums
    {
        public enum Level : byte
        {
            [EnumMember(Value = "None")] NONE = 0,
            [EnumMember(Value = "Baby 1")] BABY1,
            [EnumMember(Value = "Baby 2")] BABY2,
            [EnumMember(Value = "Child")] CHILD,
            [EnumMember(Value = "Adult")] ADULT,
            [EnumMember(Value = "Perfect")] PERFECT,
            [EnumMember(Value = "Ultimate")] ULTIMATE,
            [EnumMember(Value = "Unused")] UNUSED,
        }
        
        public enum DigimonNames : short
        {
            Dodomon = 1,
            Botamon = 2,
            Jarimon = 3,
            Yuramon = 4,
            Poyomon = 5,
            Wanyamon = 6,
            Koromon = 7,
            Gigimon = 8,
            Budmon = 9,
            Tokomon = 10,
            Hagurumon = 11,
            Candlemon = 12,
            Chuumon = 13,
            Tsukaimon = 14,
            Agumon = 15,
            Kamemon = 16,
            Kudamon = 17,
            Gaomon = 18,
            Lalamon = 19,
            Impmon = 20,
            Guilmon = 21,
            Patamon = 22,
            DemiDevimon = 23,
            BlackGabumon = 24,
            Psychemon = 25,
            Goburimon = 26,
            Dorumon = 27,
            Veemon = 28,
            SnowAgumon = 29,
            BlackAgumon = 30,
            Gabumon = 31,
            Solarmon = 33,
            Tentomon = 35,
            Biyomon = 36,
            Meramon = 37,
            Airdramon = 38,
            Garurumon = 39,
            Bakemon = 40,
            Whamon = 43,
            BlackGatomon = 45,
            GeoGreymon = 47,
            Sunflowmon = 48,
            Gaogamon = 49,
            Numemon = 50,
            Leomon = 51,
            Growlmon = 53,
            Angemon = 54,
            Growlmon_Orange = 55,
            Gatomon = 56,
            Devimon = 57,
            BlackGrowlmon = 58,
            IceDevimon = 59,
            BlackGarurumon = 61,
            Gururumon = 62,
            Geremon = 63,
            Kabuterimon = 66,
            Birdramon = 67,
            Sukamon = 68,
            Vegiemon = 69,
            Greymon = 70,
            Lucemon_FM = 72,
            Monzaemon = 74,
            RizeGreymon = 75,
            Lilamon = 76,
            MachGaogamon = 77,
            Myotismon = 81,
            Stingmon = 82,
            MagnaAngemon = 83,
            LadyDevimon = 84,
            MegaSeadramon = 85,
            WarGrowlmon = 87,
            B_WarGrowlmon = 88,
            WereGarurumon = 89,
            Angewomon = 90,
            BlueMeramon = 91,
            B_WereGarurumon = 92,
            WarGrowlmon_Orange = 95,
            Megadramon = 97,
            MetalGreymon = 98,
            MegaKabuterimon = 99,
            Garudamon = 100,
            Etemon = 101,
            MarineAngemon = 102,
            WarGreymon = 103,
            Lilithmon = 104,
            Beelzemon = 105,
            Barbamon = 106,
            Leviamon = 107,
            Daemon = 108,
            Belphemon = 109,
            Chaosmon = 110,
            Darkdramon = 111,
            BanchoLeomon = 112,
            Rosemon = 113,
            PlatinumNumemon = 114,
            Omegamon = 116,
            ShineGreymon = 117,
            MirageGaogamon = 118,
            WarGreymon_X = 120,
            Gallantmon = 121,
            MetalGarurumon = 122,
            ChaosGallantmon = 123,
            BlackWarGreymon = 124,
            BlackMetalGarurumon = 125,
            ZeedGarurumon = 131,
            VictoryGreymon = 132,
            Examon = 136,
            Jijimon = 137,
            HerculesKabuterimon = 138,
            Phoenixmon = 139,
            MetalEtemon = 140,
            Seraphimon = 141,
            MetalGreymon_Virus = 142,
            Apocalymon = 143,
            Vitium = 144,
            Vitium2 = 145,
            Vitium3 = 146,
            Vitium4 = 147,
            BlackWarGreymon_X = 148,
            Agumon_Special_Version = 149,
            Guardromon = 150,
            Andromon = 151,
            Gomamon = 152,
            Ikkakumon = 153,
            Zudomon = 154,
            Vikemon = 155,
            Seadramon = 156,
            Palmon = 157,
            Togemon = 158,
            Examon_Boss = 159,
            Monzaemon_Alternate_Color = 160,
            Rosemon_X = 161,
            Agumon_X = 162,
            Greymon_X = 163,
            Seadramon_X = 164,
            Gomamon_X = 165,
            Omegamon_X = 166,
            Gallantmon_X = 167,
            Lillymon = 168,
            Yggdrasill = 169,
            Salamon = 170,
            Salamon_X = 171,
            Tyrannomon = 172,
            MetalTyrannomon = 173,
            ExVeemon = 174,
            Dexmon = 175,
            Kuwagamon = 176,
            Shellmon = 177,
            Monochromon = 178,
            Frigimon = 179,
            Mojyamon = 180,
            Centarumon = 181,
            Drimogemon = 182,
            Digitamamon = 183,
            Nanimon = 184,
            ShogunGekomon = 185,
            Wizardmon = 186,
            Deramon = 187,
            Cherrymon = 188,
            Garbagemon = 189,
            WaruMonzaemon = 190,
            Magnamon = 191,
            RustTyrannomon = 192,
            Agumon_2006 = 193,
            Machinedramon = 194,
            Pabumon = 195,
            Motimon = 196,
            Betamon = 197,
            Lucemon = 198,
            Renamon = 199,
            Wormmon = 200,
            Woodmon = 201,
            Ogremon = 202,
            Kyubimon = 203,
            Dorugamon = 204,
            Veedramon = 205,
            Clockmon = 206,
            Gekomon = 207,
            AeroVeedramon = 208,
            Okuwamon = 209,
            Gigadramon = 210,
            GrapLeomon = 211,
            SkullGreymon = 212,
            Taomon = 213,
            SkullMeramon = 214,
            DoruGreymon = 215,
            Paildramon = 216,
            IceLeomon = 217,
            Piximon = 218,
            Vademon = 219,
            Mamemon = 220,
            MetalMamemon = 221,
            Parrotmon = 222,
            MasterTyrannomon = 223,
            Alphamon = 224,
            UlforceVeedramon = 225,
            UlforceVeedramon_X = 226,
            Imperialdramon_FM = 227,
            Imperialdramon_PM = 228,
            Ophanimon = 229,
            Chaosdramon = 230,
            GrandKuwagamon = 231,
            SaberLeomon = 232,
            Sakuyamon = 233,
            Hi_Andromon = 234,
            Piedmon = 235,
            Puppetmon = 236,
            PrinceMamemon = 237,
            Beelzemon_X = 238,
            Boltmon = 239,
            Magnamon_X = 240,
            MetalGarurumon_X = 241,
            MetalSeadramon = 242,
            Lucemon_Satan_Mode = 243,
            Punimon = 244,
            Tsunomon = 245,
            Belphemon_Sleep_Mode = 246,
            Titamon = 247,
        }
        public enum Skills
        {
            None = 0,
            Fire_Breath = 1,
            Fire_Tower = 2,
            Fire_Wall = 3,
            Mine = 4,
            Spread_Bomb = 5,
            Magma_Bomb = 6,
            Flame_Storm = 7,
            Bubble_Breath = 8,
            Hailstone = 9,
            Splash = 10,
            Waterfall = 11,
            Heavy_Rain = 12,
            Ice_Statue = 13,
            Aurora_Freeze = 14,
            Electric_Shoot = 15,
            Wind_Shoes = 16,
            Air_Cutter = 17,
            Electric_Cloud = 18,
            Thunderstorm = 19,
            Confuse_Storm = 20,
            Hurricane = 21,
            Poison_Powder = 22,
            Earth_Coat = 23,
            Poison_Circle = 24,
            Roots_Bind = 25,
            Rock_Fall = 26,
            Land_Slide = 27,
            Poison_Storm = 28,
            Mach_Jab = 29,
            Muscle_Charge = 30,
            Spin_Attack = 31,
            Heavy_Impact = 32,
            War_Cry = 33,
            Charge_Attack = 34,
            Fighting_Aura = 35,
            Dark_Spirit = 36,
            Light_Soul = 37,
            Loose_Cloud = 38,
            Flash = 39,
            Evil_Squall = 40,
            Holy_Sunshine = 41,
            Judgment = 42,
            Mechanical_Claw = 43,
            Upgrade = 44,
            Energy_Ball = 45,
            AntiAttack_Field = 46,
            Heavy_Laser = 47,
            Machine_Fall = 48,
            DG_Dimension_V2 = 49,
            Dirty_Kick = 50,
            Ultra_Stink_Spray = 51,
            Poop_Trap = 52,
            Poop_Barrier = 53,
            Random_Poop_Toss = 54,
            Poop_Fall = 55,
            Ultimate_Poop_Hell = 56,
            Bubbles = 57,
            Deadly_Counter = 58,
            Data_Wave = 59,
            Access_Block = 60,
            Lossy_Compression = 61,
        }

        public enum Attribute : byte
        {
            [EnumMember(Value = "None")] NONE = 0,
            [EnumMember(Value = "Data")] DATA,
            [EnumMember(Value = "Vaccine")] VACCINE,
            [EnumMember(Value = "Virus")] VIRUS,
            [EnumMember(Value = "Free")] FREE,
            [EnumMember(Value = "Unknown")] UNKNOWN,
        }

        public enum Special : byte
        {
            [EnumMember(Value = "None")] NONE = 0,
            [EnumMember(Value = "Fire")] FIRE,
            [EnumMember(Value = "Water")] WATER,
            [EnumMember(Value = "Air")] AIR,
            [EnumMember(Value = "Nature")] NATURE,
            [EnumMember(Value = "Combat")] COMBAT,
            [EnumMember(Value = "Light")] LIGHT,
            [EnumMember(Value = "Dark")] DARK,
            [EnumMember(Value = "Mech")] MECH,
            [EnumMember(Value = "Filth")] FILTH,
            [EnumMember(Value = "Neutral")] NEUTRAL,
        }


    }
}
